version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/models/yolov11s.pt
      - DEVICE=cpu
    volumes:
      - ./models:/models:ro
    restart: unless-stopped